package com.lizl.mydiary.constant

object AppConstant
{
    const val BUNDLE_DATA_OBJECT = "BUNDLE_DATA_OBJECT"
    const val BUNDLE_DATA_STRING_ARRAY = "BUNDLE_DATA_STRING_ARRAY"
    const val BUNDLE_DATA_STRING = "BUNDLE_DATA_STRING"
    const val BUNDLE_DATA_BOOLEAN = "BUNDLE_DATA_BOOLEAN"
    const val BUNDLE_DATA_INT = "BUNDLE_DATA_INT"

    const val MOOD_ALL = 0
    const val MOOD_HAPPY = 1
    const val MOOD_NORMAL = 2
    const val MOOD_UNHAPPY = 3

    const val RESTORE_DATA_FAILED_WRONG_PASSWORD = "RESTORE_DATA_FAILED_WRONG_PASSWORD"
    const val RESTORE_DATA_FAILED_WRONG_BACKUP_FILE = "RESTORE_DATA_FAILED_WRONG_BACKUP_FILE"
}