package com.lizl.mydiary.config

object ConfigConstant
{
    // 指纹解锁是否开启
    const val IS_FINGERPRINT_LOCK_ON = "IS_FINGERPRINT_LOCK_ON"
    const val DEFAULT_IS_FINGERPRINT_LOCK_ON = false

    // 密码保护是否开启
    const val IS_APP_LOCK_ON = "IS_APP_LOCK_ON"
    const val DEFAULT_IS_APP_LOCK_ON = false

    // APP保护密码
    const val APP_LOCK_PASSWORD = "APP_LOCK_PASSWORD"
    const val DEFAULT_APP_LOCK_PASSWORD = ""

    // APP上次停止的时间（用于判断是否达到超时锁定时长）
    const val APP_LAST_STOP_TIME = "APP_LAST_STOP_TIME"
    const val DEFAULT_APP_LAST_STOP_TIME: Long = 0

    // APP超时锁定时长
    const val APP_TIMEOUT_PERIOD = "APP_TIMEOUT_PERIOD"
    const val APP_TIMEOUT_PERIOD_RIGHT_NOW = 0L
    const val APP_TIMEOUT_PERIOD_1_MINUTE = 1 * 60 * 1000L
    const val APP_TIMEOUT_PERIOD_5_MINUTE = 5 * 60 * 1000L
    const val APP_TIMEOUT_PERIOD_10_MINUTE = 10 * 60 * 1000L
    const val DEFAULT_APP_TIMEOUT_PERIOD = APP_TIMEOUT_PERIOD_5_MINUTE

    // 夜间模式
    const val APP_NIGHT_MODE = "APP_NIGHT_MODE"
    const val APP_NIGHT_MODE_ON = 1
    const val APP_NIGHT_MODE_OFF = 2
    const val APP_NIGHT_MODE_FOLLOW_SYSTEM = 3
    const val DEFAULT_APP_NIGHT_MODE = APP_NIGHT_MODE_FOLLOW_SYSTEM

    // 自动备份
    const val IS_AUTO_BACKUP_ON = "IS_AUTO_BACKUP_ON"
    const val DEFAULT_IS_AUTO_BACKUP_ON = false

    // 上次自动备份时间
    const val APP_LAST_AUTO_BACKUP_TIME = "APP_LAST_AUTO_BACKUP_TIME"
    const val DEFAULT_APP_LAST_AUTO_BACKUP_TIME: Long = 0

    // 自动备份间隔
    const val APP_AUTO_BACKUP_PERIOD = "APP_AUTO_BACKUP_PERIOD"
    const val APP_AUTO_BACKUP_PERIOD_RIGHT_NOW = 0L
    const val APP_AUTO_BACKUP_PERIOD_1_DAY = 24 * 60 * 60 * 1000L
    const val APP_AUTO_BACKUP_PERIOD_1_WEEK = 7 * 24 * 60 * 60 * 1000L
    const val APP_AUTO_BACKUP_PERIOD_1_MONTH = 30 * 24 * 60 * 60 * 1000L
    const val DEFAULT_APP_AUTO_BACKUP_PERIOD = APP_AUTO_BACKUP_PERIOD_1_DAY

    // 备份文件加密
    const val IS_BACKUP_FILE_ENCRYPTION = "IS_BACKUP_FILE_ENCRYPTION"
    const val DEFAULT_IS_BACKUP_FILE_ENCRYPTION = false

    // 段首缩进
    const val LAYOUT_STYLE_PARAGRAPH_HEAD_INDENT = "LAYOUT_STYLE_PARAGRAPH_HEAD_INDENT"
    const val DEFAULT_LAYOUT_STYLE_PARAGRAPH_HEAD_INDENT = true

    // 日记TAG
    const val LAYOUT_STYLE_SHOW_DIARY_TAG = "LAYOUT_STYLE_SHOW_DIARY_TAG"
    const val DEFAULT_LAYOUT_STYLE_SHOW_DIARY_TAG = false

    // 图片数量
    const val LAYOUT_STYLE_IMAGE_COUNT = "LAYOUT_STYLE_IMAGE_COUNT"
    const val DEFAULT_LAYOUT_STYLE_IMAGE_COUNT = 9

    // 图片保存质量
    const val IMAGE_SAVE_QUALITY_LOW = 30
    const val IMAGE_SAVE_QUALITY_MEDIUM = 60
    const val IMAGE_SAVE_QUALITY_ORIGINAL = 100
    const val IMAGE_SAVE_QUALITY = "IMAGE_SAVE_QUALITY"
    const val DEFAULT_IMAGE_SAVE_QUALITY = IMAGE_SAVE_QUALITY_ORIGINAL
}